#!/usr/bin/env bash
#
# convert-to-gguf.sh — Convert Heretic output (safetensors) to GGUF,
#                      then create an Ollama Modelfile.
#
# Prerequisites:
#   - llama.cpp cloned and built (or installed via pip/brew)
#   - ollama installed (for `ollama create`)
#
# Usage:
#   ./scripts/convert-to-gguf.sh <output-dir>
#   ./scripts/convert-to-gguf.sh output/google--gemma-3-12b-it-abliterated
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Config ────────────────────────────────────────────────────────────────────
GGUF_TYPE="${GGUF_TYPE:-f16}"               # f16, q8_0, q4_k_m, etc.
LLAMA_CPP_DIR="${LLAMA_CPP_DIR:-$PROJECT_ROOT/llama.cpp}"
OUTPUT_BASE="${1:-}"

if [[ -z "$OUTPUT_BASE" ]]; then
    echo "❌ Usage: $0 <output-dir>"
    echo "   Example: $0 output/google--gemma-3-12b-it-abliterated"
    exit 1
fi

if [[ ! -d "$OUTPUT_BASE" ]]; then
    echo "❌ Directory not found: $OUTPUT_BASE"
    exit 1
fi

# ── Locate llama.cpp ──────────────────────────────────────────────────────────
CONVERT_SCRIPT=""
if [[ -f "$LLAMA_CPP_DIR/convert_hf_to_gguf.py" ]]; then
    CONVERT_SCRIPT="$LLAMA_CPP_DIR/convert_hf_to_gguf.py"
elif command -v convert_hf_to_gguf.py &>/dev/null; then
    CONVERT_SCRIPT="$(command -v convert_hf_to_gguf.py)"
else
    echo "❌ llama.cpp not found."
    echo "   Clone it:  git clone https://github.com/ggerganov/llama.cpp.git $LLAMA_CPP_DIR"
    echo "   Or set:    LLAMA_CPP_DIR=/path/to/llama.cpp"
    exit 1
fi

echo "🔧 Converting safetensors → GGUF"
echo "   Input:     $OUTPUT_BASE"
echo "   llama.cpp: $CONVERT_SCRIPT"
echo ""

# ── Convert to GGUF ───────────────────────────────────────────────────────────
GGUF_OUTPUT="${OUTPUT_BASE}.gguf"

python3 "$CONVERT_SCRIPT" \
    "$OUTPUT_BASE" \
    --outfile "$GGUF_OUTPUT" \
    --outtype "$GGUF_TYPE"

echo ""
echo "✅ GGUF written: $GGUF_OUTPUT"

# ── Quantize (optional, for smaller files) ────────────────────────────────────
if [[ -n "${QUANTIZE:-}" ]]; then
    QUANT_OUTPUT="${OUTPUT_BASE}-${QUANTIZE}.gguf"
    if [[ -x "$LLAMA_CPP_DIR/llama-quantize" ]]; then
        echo "🔢 Quantizing to $QUANTIZE ..."
        "$LLAMA_CPP_DIR/llama-quantize" "$GGUF_OUTPUT" "$QUANT_OUTPUT" "$QUANTIZE"
        GGUF_OUTPUT="$QUANT_OUTPUT"
        echo "✅ Quantized: $GGUF_OUTPUT"
    else
        echo "⚠ llama-quantize not found at $LLAMA_CPP_DIR/llama-quantize — skipping quantization"
    fi
fi

# ── Create Ollama Modelfile ───────────────────────────────────────────────────
MODELFILE="$OUTPUT_BASE/Modelfile"
GGUF_FILENAME="$(basename "$GGUF_OUTPUT")"

# Copy GGUF into the model directory for Ollama
cp "$GGUF_OUTPUT" "$OUTPUT_BASE/$GGUF_FILENAME"

cat > "$MODELFILE" <<EOF
# Ollama Modelfile — auto-generated by convert-to-gguf.sh
# Model: $(basename "$OUTPUT_BASE")

FROM ./$GGUF_FILENAME

PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER num_ctx 8192

# System prompt — adjust to your needs
SYSTEM You are a helpful, knowledgeable AI assistant. Respond thoroughly and accurately.
EOF

echo "📝 Modelfile created: $MODELFILE"
echo ""
echo "─── Next Steps ────────────────────────────────────"
echo "  cd $OUTPUT_BASE"
echo "  ollama create $(basename "$OUTPUT_BASE") -f Modelfile"
echo "  ollama run $(basename "$OUTPUT_BASE")"
echo "───────────────────────────────────────────────────"
